/*
 * Copyright Strimzi authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */
package io.strimzi.test.container;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testcontainers.containers.Container;
import org.testcontainers.images.builder.Transferable;

import java.io.IOException;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Collection;

/**
 * Encapsulates all TLS certificate lifecycle operations for a Kafka cluster:
 *  i.   generation via keytool,
 *  ii.  extraction from containers and
 *  iii. distribution to brokers.
 *
 * Uses two self-signed Certificate Authorities (CAs) to form
 * separate trust domains:
 *  i.   A cluster CA that signs broker and internal
 *       certificates (inter-broker and controller traffic).
 *  ii.  A clients CA that signs client certificates
 *       (mTLS authentication).
 *
 * The broker truststore for the external listener contains the clients CA (to verify
 * client certs during mTLS), while the client truststore
 * contains the cluster CA (to verify the broker's identity).
 * Additionally, the broker truststore for the internal listener contains the cluster
 * CA (to verify the other broker's identities).
 *
 * Manages three pairs of PKCS12 stores:
 *  i.   Broker stores, deployed at
 *       {@value #BROKER_KEYSTORE_PATH} and
 *       {@value #BROKER_TRUSTSTORE_PATH}.
 *       Used by the client-facing listener.
 *  ii.  Internal stores, deployed at
 *       {@value #INTERNAL_KEYSTORE_PATH} and
 *       {@value #INTERNAL_TRUSTSTORE_PATH}.
 *       Used by inter-broker and controller
 *       listeners.
 *  iii. Client stores, exposed to test code via
 *       {@link StrimziKafkaCluster} for mTLS.
 *
 * Each keystore holds a CA-signed certificate and
 * private key. Each truststore holds the CA
 * certificate.
 *
 * Each component (broker, internal, client) uses its own
 * independently generated password.
 */
class CertAssembly {

    private static final Logger LOGGER = LoggerFactory.getLogger(CertAssembly.class);

    /**
     * Path to the broker keystore inside the container.
     */
    static final String BROKER_KEYSTORE_PATH =
        "/opt/kafka/config/server.keystore.p12";

    /**
     * Path to the broker truststore inside the container.
     */
    static final String BROKER_TRUSTSTORE_PATH =
        "/opt/kafka/config/server.truststore.p12";

    /**
     * Path to the internal keystore inside the container.
     */
    static final String INTERNAL_KEYSTORE_PATH =
        "/opt/kafka/config/internal.keystore.p12";

    /**
     * Path to the internal truststore inside the container.
     */
    static final String INTERNAL_TRUSTSTORE_PATH =
        "/opt/kafka/config/internal.truststore.p12";

    private byte[] brokerKeyStoreBytes;
    private byte[] brokerTrustStoreBytes;
    private final String brokerPassword;
    private byte[] internalKeyStoreBytes;
    private byte[] internalTrustStoreBytes;
    private final String internalPassword;
    private byte[] clientKeyStoreBytes;
    private byte[] clientTrustStoreBytes;
    private final String clientPassword;

    private CertAssembly(String brokerPassword, String internalPassword, String clientPassword) {
        this.brokerPassword = brokerPassword;
        this.internalPassword = internalPassword;
        this.clientPassword = clientPassword;
    }

    /**
     * Creates a CertAssembly for auto-generated certificates with a randomly generated password.
     * Certificates will be generated inside a container via keytool during {@link #setupTlsCerts}.
     *
     * @return a new CertAssembly instance
     */
    static CertAssembly autoGenerated() {
        return new CertAssembly(generatePassword(), generatePassword(), generatePassword());
    }

    private static String generatePassword() {
        final SecureRandom random = new SecureRandom();
        final byte[] bytes = new byte[16];
        random.nextBytes(bytes);
        final StringBuilder sb = new StringBuilder();
        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }


    /**
     * Sets up TLS certificates for all nodes in the cluster auto-generated (i.e.,
     * generates certificates via keytool on the first node, extracts them,
     * and distributes to all nodes).
     *
     * @param nodes      the containers to distribute certificates to
     * @param totalNodes the total number of nodes (used for SAN generation)
     */
    @DoNotMutate
    void setupTlsCerts(Collection<StrimziKafkaContainer> nodes, int totalNodes) {
        if (this.brokerKeyStoreBytes == null) {
            StrimziKafkaContainer firstNode = nodes.iterator().next();

            LOGGER.info("Generating TLS certificates via keytool on first node (node {})", firstNode.getNodeId());
            generateCertsOnBroker(firstNode, totalNodes);

            this.brokerKeyStoreBytes = extractFileFromBroker(
                firstNode, "/tmp/server.keystore.p12");
            this.brokerTrustStoreBytes = extractFileFromBroker(
                firstNode, "/tmp/server.truststore.p12");
            this.internalKeyStoreBytes = extractFileFromBroker(
                firstNode, "/tmp/internal.keystore.p12");
            this.internalTrustStoreBytes = extractFileFromBroker(
                firstNode, "/tmp/internal.truststore.p12");
            this.clientKeyStoreBytes = extractFileFromBroker(
                firstNode, "/tmp/client.keystore.p12");
            this.clientTrustStoreBytes = extractFileFromBroker(
                firstNode, "/tmp/client.truststore.p12");
        }

        for (StrimziKafkaContainer node : nodes) {
            LOGGER.info("Distributing TLS certificates"
                + " to node (node {})", node.getNodeId());
            node.copyFileToContainer(
                Transferable.of(this.brokerKeyStoreBytes),
                BROKER_KEYSTORE_PATH);
            node.copyFileToContainer(
                Transferable.of(this.brokerTrustStoreBytes),
                BROKER_TRUSTSTORE_PATH);
            node.copyFileToContainer(
                Transferable.of(this.internalKeyStoreBytes),
                INTERNAL_KEYSTORE_PATH);
            node.copyFileToContainer(
                Transferable.of(this.internalTrustStoreBytes),
                INTERNAL_TRUSTSTORE_PATH);
        }

        LOGGER.info("TLS certificates distributed to all {} nodes", nodes.size());
    }

    /**
     * Generates TLS certificates via keytool inside a running
     * broker container using two self-signed CAs:
     * a cluster CA for broker/internal certs and a clients CA
     * for client certs.
     * Files are generated in /tmp/ to avoid permission issues.
     *
     * @param broker     the container to generate certs on
     * @param totalNodes the number of nodes to include in SANs
     */
    @DoNotMutate
    private void generateCertsOnBroker(StrimziKafkaContainer broker, int totalNodes) {
        String clusterCaKeystore = "/tmp/cluster-ca.p12";
        String clusterCaCert = "/tmp/cluster-ca.crt";
        String clientsCaKeystore = "/tmp/clients-ca.p12";
        String clientsCaCert = "/tmp/clients-ca.crt";

        String sans = "SAN=" + buildSans(totalNodes);

        try {
            Keytool keytool = new Keytool(broker);

            // create self-signed certificate authorities
            createCa(keytool, clusterCaKeystore, clusterCaCert,
                "CN=strimzi-cluster-ca,O=Strimzi,C=US",
                this.brokerPassword);
            createCa(keytool, clientsCaKeystore, clientsCaCert,
                "CN=strimzi-clients-ca,O=Strimzi,C=US",
                this.clientPassword);

            // broker certificate, signed by cluster-ca
            createSignedCert(keytool,
                clusterCaKeystore, clusterCaCert, this.brokerPassword,
                "/tmp/server.keystore.p12", "broker",
                "CN=kafka-broker,O=Strimzi,C=US",
                "/tmp/broker.csr", "/tmp/broker-signed.crt",
                this.brokerPassword, sans);

            // internal certificate, signed by cluster-ca
            createSignedCert(keytool,
                clusterCaKeystore, clusterCaCert, this.brokerPassword,
                "/tmp/internal.keystore.p12", "internal",
                "CN=kafka-internal,O=Strimzi,C=US",
                "/tmp/internal.csr", "/tmp/internal-signed.crt",
                this.internalPassword, sans);

            // client certificate, signed by clients-ca
            createSignedCert(keytool,
                clientsCaKeystore, clientsCaCert, this.clientPassword,
                "/tmp/client.keystore.p12", "client",
                "CN=kafka-client,O=Strimzi,C=US",
                "/tmp/client.csr", "/tmp/client-signed.crt",
                this.clientPassword, null);

            // broker truststore, contains clients-ca (i.e., for verification client mTLS certs)
            keytool.importTrustedCertificate()
                .keystore("/tmp/server.truststore.p12")
                .password(this.brokerPassword)
                .alias("ca")
                .fromFile(clientsCaCert)
                .execute();
            // internal truststore, contains cluster-ca (i.e., for verification inter-broker certs)
            keytool.importTrustedCertificate()
                .keystore("/tmp/internal.truststore.p12")
                .password(this.internalPassword)
                .alias("ca")
                .fromFile(clusterCaCert)
                .execute();
            // client truststore, contains cluster-ca (i.e., for verification broker identity)
            keytool.importTrustedCertificate()
                .keystore("/tmp/client.truststore.p12")
                .password(this.clientPassword)
                .alias("ca")
                .fromFile(clusterCaCert)
                .execute();

            LOGGER.info("Generated TLS certificates via keytool (cluster-ca: broker + internal, clients-ca: client)");
        } catch (IOException | InterruptedException e) {
            if (e instanceof InterruptedException) {
                Thread.currentThread().interrupt();
            }
            throw new RuntimeException(
                "Failed to generate TLS certificates", e);
        }
    }

    /**
     * Creates a self-signed CA: generates a key pair with CA
     * extensions and exports the certificate to a file.
     */
    private void createCa(Keytool keytool,
                           String caKeystore,
                           String caCert,
                           String dname,
                           String password)
            throws IOException, InterruptedException {
        keytool.generateKeyPair()
            .keystore(caKeystore)
            .password(password)
            .alias("ca")
            .dname(dname)
            .asCa()
            .execute();
        keytool.exportCertificate()
            .keystore(caKeystore)
            .password(password)
            .alias("ca")
            .toFile(caCert)
            .execute();
    }

    /**
     * Creates a CA-signed certificate: generates a key pair, creates
     * a CSR, signs it with the CA, and imports both the CA certificate
     * and the signed certificate into the entity keystore.
     */
    @SuppressWarnings("ParameterNumber")
    private void createSignedCert(Keytool keytool,
                                  String caKeystore,
                                  String caCert,
                                  String caPassword,
                                  String keystore,
                                  String alias,
                                  String dname,
                                  String csrFile,
                                  String signedCertFile,
                                  String password,
                                  String sans)
        throws IOException, InterruptedException {
        keytool.generateKeyPair()
            .keystore(keystore)
            .password(password)
            .alias(alias)
            .dname(dname)
            .execute();
        keytool.generateCertificateSigningRequest()
            .keystore(keystore)
            .password(password)
            .alias(alias)
            .toFile(csrFile)
            .execute();
        Keytool.SignCertificateCommand signCmd =
            keytool.signCertificateRequest()
                .caKeystore(caKeystore)
                .caPassword(caPassword)
                .csrFile(csrFile)
                .signedCertFile(signedCertFile);
        if (sans != null) {
            signCmd.withSans(sans);
        }
        signCmd.execute();
        keytool.importTrustedCertificate()
            .keystore(keystore)
            .password(password)
            .alias("ca")
            .fromFile(caCert)
            .execute();
        keytool.importSignedCertificate()
            .keystore(keystore)
            .password(password)
            .alias(alias)
            .fromFile(signedCertFile)
            .execute();
    }

    private StringBuilder buildSans(int totalNodes) {
        StringBuilder sans =
            new StringBuilder("DNS:localhost,DNS:*.localhost");
        for (int i = 0; i < totalNodes; i++) {
            sans.append(",DNS:")
                .append(StrimziKafkaContainer.NETWORK_ALIAS_PREFIX)
                .append(i);
        }
        sans.append(",IP:127.0.0.1");
        return sans;
    }

    /**
     * Extracts a file from a running broker container as a byte array.
     *
     * @param broker        the broker container to extract from
     * @param containerPath the path of the file inside the container
     * @return the file contents as a byte array
     */
    @DoNotMutate
    private byte[] extractFileFromBroker(StrimziKafkaContainer broker, String containerPath) {
        try {
            Container.ExecResult result = broker.execInContainer("base64", containerPath);
            if (result.getExitCode() != 0) {
                throw new RuntimeException("Failed to extract file " + containerPath + " from container: " + result.getStderr());
            }
            String encoded = result.getStdout().replaceAll("\\s", "");
            return Base64.getDecoder().decode(encoded);
        } catch (IOException | InterruptedException e) {
            if (e instanceof InterruptedException) {
                Thread.currentThread().interrupt();
            }
            throw new RuntimeException("Failed to extract file from container", e);
        }
    }

    /**
     * Gets the client keystore bytes for mTLS authentication.
     *
     * @return the client keystore as a byte array in PKCS12 format, or null if not yet generated
     */
    byte[] getClientKeyStoreBytes() {
        return this.clientKeyStoreBytes != null ? this.clientKeyStoreBytes.clone() : null;
    }

    /**
     * Gets the client truststore bytes containing the broker certificate.
     * Clients use this to verify the broker's identity.
     *
     * @return the client truststore as a byte array in PKCS12 format, or null if not yet generated
     */
    byte[] getClientTrustStoreBytes() {
        return this.clientTrustStoreBytes != null ? this.clientTrustStoreBytes.clone() : null;
    }

    /**
     * Gets the broker keystore/truststore password.
     *
     * @return the broker password
     */
    String getBrokerPassword() {
        return this.brokerPassword;
    }

    /**
     * Gets the internal keystore/truststore password.
     *
     * @return the internal password
     */
    String getInternalPassword() {
        return this.internalPassword;
    }

    /**
     * Gets the client keystore/truststore password.
     *
     * @return the client password
     */
    String getClientPassword() {
        return this.clientPassword;
    }
}
