# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
  tags:
    include:
      - '*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

jobs:
  - job: 'main_branch_build'
    displayName: 'Build'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: 'Ubuntu-18.04'
    # Pipeline steps
    steps:
      - task: Cache@2
        inputs:
          key: 'mvn-m2-cache | $(System.JobName)'
          path: "$(MVN_CACHE_FOLDER)"
        displayName: Maven cache
      - bash: |
          sudo apt-get update
        displayName: 'Update package list'

      - bash: |
         sudo apt-get install openjdk-8-jdk
        displayName: 'Install openjdk8'

      - bash: |
         echo "##vso[task.setvariable variable=JAVA_VERSION_BUILD]1.8"
         echo "##vso[task.setvariable variable=JAVA_VERSION]1.8.0"
        displayName: 'Setup JAVA_VERSION=1.8'

      - bash: |
         echo "##vso[task.setvariable variable=JAVA_HOME]$(JDK_PATH)"
         echo "##vso[task.setvariable variable=JAVA_HOME__X64]$(JDK_PATH)"
         echo "##vso[task.setvariable variable=PATH]$(jdk_path)/bin:$(PATH)"
        displayName: 'Setup JAVA_HOME'

      - bash: mvn clean install -Dmaven.javadoc.skip=true -DskipTests=true
        displayName: "Strimzi test container build"

      - bash: |
          export TESTCONTAINERS_RYUK_DISABLED=TRUE
          export TESTCONTAINERS_CHECKS_DISABLE=TRUE
        displayName: "Test container optimization"

      - bash: mvn verify -Dmaven.javadoc.skip=true
        displayName: "Strimzi test container verify"

      - task: PublishTestResults@2
          inputs:
            testResultsFormat: JUnit
            testResultsFiles: '**/TEST-*.xml'
            testRunTitle: "Integration tests"
          condition: always()